name = "v0-job-application-tracker"
compatibility_date = "2024-03-23"

[build]
command = "pnpm build"
output_directory = ".next"

[site]
bucket = ".next"

[env.production]
name = "v0-job-application-tracker"
workers_dev = true
route = ""
zone_id = ""

[env.production.vars]
NODE_ENV = "production" 